### ISSUE TITLE
'Join Event' feature not working

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#100]
**Describe the bug**
The 'Join Event' box where users add their names to join an event hosted on BigBlueButton (BBB) is not showing.

**To Reproduce**
1. Go to an event page for an event hosted on BBB, like [this](https://www.josa.ngo/events/112/josa-techtalks-in-depth-web-application-defense-using-csp).
2. Optionally, check the URL for joining the event (with `?join` after the URL), like [this](https://www.josa.ngo/events/112/josa-techtalks-in-depth-web-application-defense-using-csp?join).

**Expected behavior**
If the event is running, a small form should appear in the side after event details, allowing users to join.
If a URL for joining the event is requested, a popup is shown with a similar form (if the event is running), if the event is not running, the popup contains a not that the event has not started yet.

**Screenshots**
N/A

**Additional context**
Check the BBB APIs.

**Comment by thread-koder** [comment]
This issue has been fixed
