### ISSUE TITLE
Menu items should follow the order in the list

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#123]
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/378.

Menu items should be displayed as they are positioned in the admin interface.
The following images show the issue, as Menu Items are stored in Strapi in a specific order, however they are displayed in a different order on the website:

On the admin interface:
![128870621-678aca1a-e80e-4b2c-af30-f2899b48c303](https://user-images.githubusercontent.com/79845228/152673277-f135d255-a2cd-4e37-86fd-2893202e8794.png)

On the website:
![128870699-dcd9559b-c41f-4610-9708-21dfcaef39ea](https://user-images.githubusercontent.com/79845228/152673300-81de36e4-0595-4c27-a5a2-2819fe479ea1.png)

**Comment by mahasneh** [comment]
Fixed in #144 v2.0.2
