### ISSUE TITLE
Allow admins to add/edit pages' og:image tag

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#126]
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/334.

Admins should be allowed to add og:image tags for:

    Pages (Page Metas)
    Info pages
    Programs

Different images for Arabic/English should be considered.

**Comment by thread-koder** [comment]
@alsahawneh This is a duplicate for Issue #114, please check if the issue already exists before adding one, I will close this issue with that in mind.
