### ISSUE TITLE
Events can still be registered for after they have finished

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#128]
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/429.

**Describe the bug**
Registration form still available even after an event has been concluded

**Expected behavior**
Registration form should noty be displayed after an event has been concluded

**Screenshots**
![139887562-531f2bff-e438-42df-b5cb-de0c938377e7](https://user-images.githubusercontent.com/79845228/152674510-5e409fea-b8bf-43d5-babc-a83f1f878e5a.png)

**Comment by mahasneh** [comment]
Closed in #144 v2.0.2
