### ISSUE TITLE
CSS elements overlapping problem in our team page

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#136]
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/390.

When a team member's name and position reserve more lines, overlapping occurs between their social accounts and their position.

![131126579-4607c7c8-ec30-496a-97f7-99fc38532309](https://user-images.githubusercontent.com/79845228/152685404-6351b8f9-0f2f-4fbd-be91-a60865f99107.png)

**Comment by mahasneh** [comment]
Does not apply anymore due to the widening of `.container`
