### ISSUE TITLE
GitHub icon links our users to the legacy repository

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#159]
**Describe the bug**
GitHub icon links our users to the legacy repository.

**To Reproduce**
1. Go to the footer
2. Click on GitHub (in the social media section)
3. See error (the link directs you to the old repo instead)

**Expected behavior**
This should link users to our new repository.

**Additional context**
N/A.

**Comment by alsahawneh** [comment]
@mahasneh George thinks it would be better if we linked users to our organisation's profile on GitHub instead of the `portal-web` repo.

**Comment by mahasneh** [comment]
Yes, it's better
