### ISSUE TITLE
Wrong page padding in 'Career' single pages

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#181]
**Describe the bug**
On mobile devices / small screens, a space is shown on the side of the single pages of careers.

**To Reproduce**
1. Go to a career page like 'https://josa.ngo/careers/15/communications-assistant'
3. See error

**Expected behavior**
The content should extend to the whole page / content in small screens / mobile.

**Screenshot**
![SmartSelect_20220314-231942_Chrome.jpg](https://user-images.githubusercontent.com/7326249/158255372-c79491ed-6d73-4d15-a916-d7687af25046.jpg)

**Comment by thread-koder** [comment]
@mahasneh Hello so we should remove the padding from small/mobile screens?

**Comment by mahasneh** [comment]
Yes
