### ISSUE TITLE
CSS bug in the image size of publications' thumbnail in medium devices

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#186]
**Describe the bug**
There is a CSS bug in the image size of publications' thumbnail in medium devices. 

**To Reproduce**
1. For instance, go to the iPad view of our website `/publications`. 
2. See error.

**Expected behavior**
All images in md-screens should have the same size.

**Screenshots**
![md_screen](https://user-images.githubusercontent.com/79845228/159368659-c375737c-a605-4b59-9a2a-d19b8d9e518e.png)

**Comment by mahasneh** [comment]
Fixed in #211
