### ISSUE TITLE
Arabic names of Gregorian months should be Syriac

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#213]
Arabic names of Gregorian months should be Syriac, not Latin, like كَانُون ٱلثَّانِي, شُبَاط, etc. and not يناير, etc.

**Comment by mahasneh** [comment]
I am working on this. Do not reassign this.

**Comment by ZaidBarghouthi** [comment]
I can't believe that momentjs doesn't have a proper Arabic locale. Might have to implement one myself.

This can be accomplished using the `Intl.DateTimeFormat` API

**Comment by ZaidBarghouthi** [comment]
Fixed by #319
