### ISSUE TITLE
Reduce width and change layout of map in "contact us" page

### ISSUE THREAD

**Issue by rayasharbain** [jordanopensource/portal-web#217]
Scrolling through the contact us page, user gets stuck in the middle the mouse stops at the map and starts zooming in/out of the map. Placing it on the left-hand side in English and right-hand side in Arabic should avoid this issue.

**Comment by rayasharbain** [comment]
Map is still scrolling for me.

**Comment by alsahawneh** [comment]
@rayasharbain  I think that the changes haven't yet been pushed to the server. That's why you can't see them in our live website. 

@wissamataleh @geokhoury When will the changes go live?

**Comment by wissamataleh** [comment]
We'll deploy to production on Thursday.
