### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by ghost** [jordanopensource/portal-web#218]
Running Locally
cd josa-portal-web/
npm install
Run npm run dev 

I am unable to run this locally using the instructions provided I have the following errors in the browser

Module parse failed: Unexpected token (4:75) File was processed with these loaders: * ./node_modules/babel-loader/lib/index.js You may need an additional loader to handle the result of these loaders. | app | }, inject) { > const dir = () => app.i18n.locales.find(x => x.code === app.i18n.locale)?.dir; | | inject('dir', dir);

I have installed nan globally

**Comment by wissamataleh** [comment]
This was a compatibility issue with Nuxt and Node 14. You can see [this bug report](https://github.com/nuxt/nuxt.js/issues/7722) in Nuxt if you want to know more about it. Yet this appears to be no longer an issue, and I've been able to run this project successfully on both Node 12 and 14 without any special modifications.

**Comment by mahasneh** [comment]
@ghost's account is now deleted. I suppose no more actions are needed to make the repo run locally, so I am going to close this issue.
