### ISSUE TITLE
Fix text on github organization link in the footer

### ISSUE THREAD

**Issue by geokhoury** [jordanopensource/portal-web#232]
**Describe the bug**
The link text for the github organization in the footer currently has the text 'josa-portal-web' and it should say 'jordanopensource' to keep the design consistent with the rest of the links in the same section.

**To Reproduce**
1. Go to [josa.ngo](https://josa.ngo)
2. Scroll down to footer.
3. Look at the github organization link, it has the wrong text!

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/329810/203108024-77574a7c-5cf0-440e-9808-30c36dc59e85.png)

**Desktop (please complete the following information):**
 - Any device / any operating system / any web browser

**Comment by amartyaroy** [comment]
@geokhoury can you please assign this bug to me.I will fix it
