### ISSUE TITLE
Change fonts used as new branding guidelines

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#252]
As for JOSA's new [branding guidelines](https://github.com/jordanopensource/design-guidelines), replace all the fonts (Aleo, Lato, Almarai) with IBM Plex Sans Arabic, available [here](https://github.com/IBM/plex/tree/master/IBM-Plex-Sans-Arabic/fonts/complete).
Code and monospace should have the font IBM Plex Mono, available [here](https://github.com/IBM/plex/tree/master/IBM-Plex-Mono/fonts/complete).

**Comment by alsahawneh** [comment]
@mahasneh Should the fonts used in our blog be changed too? (Single blog posts have their own fonts, they override the fonts that are used elsewhere in the website)

**Comment by mahasneh** [comment]
@alsahawneh No, please keep the current fonts for the blog.

**Comment by alsahawneh** [comment]
@mahasneh Okey dokey!

**Comment by wissamataleh** [comment]
@mahasneh 
- Do the Arabic and English fonts mentioned in the branding guidelines need to used individually, or are they included in each others?
```
Latin: IBM Plex Sans
Arabic: IBM Plex Sans Arabic
```
- When previewed, you can see some differences between the fonts in [IBM/plex](https://github.com/IBM/plex) repo and the same font in [Adobe fonts](https://fonts.adobe.com/fonts/ibm-plex-arabic). Which one should be used? (I personaly like the preview in Adobe fonts a lot more)

**Comment by mahasneh** [comment]
The Arabic version contains Latin Characters as well.
Regarding the preview, I think they are the same identical fonts, probably Adobe has it smoother when presenting the font

**Comment by wissamataleh** [comment]
> The Arabic version contains Latin Characters as well.
> Regarding the preview, I think they are the same identical fonts, probably Adobe has it smoother when presenting the font

Some characters are different in both languages. Not really sure why.

**Comment by linuxjo** [comment]
So, the only suggested edit to PR #309 is just to use @ibm/plex node package instead of manually importing, right? 
Are there other edits that I am supposed to make regarding this issue? (See this PR: #309) 

@mahasneh @wissamataleh

**Comment by wissamataleh** [comment]
> So, the only suggested edit to PR #309 is just to use @ibm/plex node package instead of manually importing, right? 
> Are there other edits that I am supposed to make regarding this issue? (See this PR: #309) 
> 
> @mahasneh @wissamataleh 

Import the font using the node module, and fix the naming in tailwind config, then remove unused fonts, then I'll do another reviews for the other font related case properties

**Comment by linuxjo** [comment]
> Import the font using the node module, and fix the naming in tailwind config, then remove unused fonts, then I'll do another review for the other font related css properties

@wissamataleh Ok. Will change it ASAP.
