### ISSUE TITLE
Change the featured image in JOSA's Statements 

### ISSUE THREAD

**Issue by linuxjo** [jordanopensource/portal-web#256]
In some "statements" that have JOSA's logo as a featured image, posts cover our logo or part of it. Some suggestions: 
- Using a pure blue image (#4797C0) instead of JOSA's large logo image.
- Shifting the logo up (in the featured image). 
- Using a blue image that has "JOSA's star" repeated a set number of times on it.

![statement_ar](https://user-images.githubusercontent.com/79845228/114800364-43a3c080-9da2-11eb-8b12-ec2db57af221.png)

![JOSA_Statement](https://user-images.githubusercontent.com/79845228/114800384-48687480-9da2-11eb-8b0b-2e77891379ee.png)

**Comment by fmubaidien** [comment]
How would shifting up look on statements that don't hide the cover

**Comment by mahasneh** [comment]
I see there is nothing to do here, this is not the default picture. Editors should be aware of this once uploading an image to the article.

**Comment by mahasneh** [comment]
Closing this issue. No changes needed.
