### ISSUE TITLE
Allow content to be previewed before publishing

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#257]
Content like, blog posts, publications, events should have the possibility to be previewed before publishing. Content can be unpublished as well.

**Comment by wissamataleh** [comment]
@mahasneh The "draft/publish" system has been enabled in Strapi for all collections. As for the live preview we need to populate the development api and connect it to the development client.

**Comment by mahasneh** [comment]
The draft/publish system is enough

**Comment by wissamataleh** [comment]
Closed by https://github.com/jordanopensource/portal-api/pull/75
