### ISSUE TITLE
Add disclaimer in blog posts

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#261]
Blog posts that are NOT statements should display a disclaimer, with a smaller font size, at the end of the post (before the Author). The text to be used is:
English: "The views expressed in this article are those of the author and do not necessarily reflect those of the Jordan Open Source Association (JOSA)"
Arabic: "الآراء المنشورة تعبر عن رأي صاحبها ولا تعبر بالضرورة عن رأي الجمعية الأردنية للمصدر المفتوح (جوسا)"

**Comment by wissamataleh** [comment]
![115988250-5e0b4480-a5c1-11eb-9193-b17460b4764c](https://user-images.githubusercontent.com/29441168/116526071-df284b80-a8e1-11eb-9378-9b8456d9f5c6.png)
