### ISSUE TITLE
Load blog post fonts correctly

### ISSUE THREAD

**Issue by ZaidBarghouthi** [jordanopensource/portal-web#316]
It seems that the fonts used in the blog post are not included in the build neither loaded from a cdn.

 
![image](https://user-images.githubusercontent.com/26728749/116641925-645d4000-a976-11eb-8b37-28c62067ba54.png)

**Comment by mahasneh** [comment]
Can you specify more what's the problem here, as all the fonts `Almarai`, `Lato` and `UthamnNaskh` are loaded correctly from CDNs?

**Comment by mahasneh** [comment]
I am closing this issue as it's actually overridden by Issue #303 as all the blog posts' fonts are changed.
