### ISSUE TITLE
Pagination arrows in Arabic flipped

### ISSUE THREAD

**Issue by rayasharbain** [jordanopensource/portal-web#330]
Pagination arrows in the blogs and events homepage are flipped in Arabic:
![Screenshot 2021-05-04 at 14 04 22](https://user-images.githubusercontent.com/25263499/116996129-a2929080-ace3-11eb-97f3-aca0dd75304e.png)

I suggest keeping the same direction in both English and Arabic:
- numbers read left-to-right
- left-pointing arrow to the left, right-pointing arrow to the right
- right-pointing arrow indicates next page, left-pointing arrow indicates previous page

**Comment by ZaidBarghouthi** [comment]
This was fixed by #312 and already merged. Should be ok in next release.

**Comment by rayasharbain** [comment]
> This was fixed by #312 and already merged. Should be ok in next release.

Ah! Didn't notice :-) Awesome!
