### ISSUE TITLE
Meta descriptions for Info Pages and Programs should be taken from description field

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#335]
In Info Pages and Programs, the meta description should be taken from description fields (`description_en` if the page is accessed in English, and `description_ar` if the page is accessed in Arabic).

**Comment by wissamataleh** [comment]
@mahasneh @Ashaqra 
In Info Pages this is already the case, and in Programs it takes the "metaDescription" field, so "description" field can be used as a fallback

**Comment by mahasneh** [comment]
Closed by #368
