### ISSUE TITLE
Date and time changing according to time zone

### ISSUE THREAD

**Issue by fmubaidien** [jordanopensource/portal-web#347]
![image](https://user-images.githubusercontent.com/32209468/120616774-157e5b00-c48c-11eb-8955-55a791b438bc.png)

As shown in the image the date and time has changed when I changed my computer's timezone, however it then says Amman time next to it, we need to decide if we want to show the date and time according to user or according to Amman

**Comment by mahasneh** [comment]
Closed by #368
