### ISSUE TITLE
Default image must be changed

### ISSUE THREAD

**Issue by rayasharbain** [jordanopensource/portal-web#355]
Currently, if no image is uploaded on an event / career / blog page, then it defaults to the following image:
![Screenshot 2021-06-28 at 13 23 05](https://user-images.githubusercontent.com/25263499/123621995-6af02280-d814-11eb-82b0-2d8b67bcafff.png)

A look at Strapi of this page will show that there's no image uploaded indeed:
![Screenshot 2021-06-28 at 13 23 21](https://user-images.githubusercontent.com/25263499/123622051-77747b00-d814-11eb-9e37-b58b2c1cd082.png)

Could we default to this image instead?
![JOSA Website - Public Panel](https://user-images.githubusercontent.com/25263499/123622252-b1de1800-d814-11eb-84fc-43d075bc3fb9.png)

**Comment by wissamataleh** [comment]
Fixed from strapi
