### ISSUE TITLE
Fix incorrect comma in our address

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#403]
In the Arabic version of our website, if you go to the contact us page, you can see that our address is `شارع الشعب, عمان`

Well, the comma actually is not correct, the Arabic comma is inverted, upside-down: ` ، `. So what we need to do here is just to replace the English comma ` , ` with the Arabic one ` ، `. 

Eventually, our address should look like this instead: `شارع الشعب، عمان`

**Comment by rokkoo** [comment]
Hey! I would like to work on this issue if is possible :)

**Comment by fmubaidien** [comment]
Hey Alphonsoe yes of course please go ahead!!

**Comment by alsahawneh** [comment]
@rokkoo Sure. You can also check out issue #410. It's similar to this one! :)
