### ISSUE TITLE
Fix a misspelled word in the contact us page

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#410]
Although the word `إلكتروني` is a foreign word, yet it managed to make it to the "Al-Mu'jam Al-Wasit" dictionary published by The Academy of the Arabic Language in Cairo. 

Usually, there aren't strict rules governing how foreign words should be written in Arabic, but it remains better to write this word the same way it is written in [Al-Mu'jam Al-Wasit](https://www.almaany.com/ar/dict/ar-ar/%D8%A5%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86/?c=%D8%A7%D9%84%D9%85%D8%B9%D8%AC%D9%85%20%D8%A7%D9%84%D9%88%D8%B3%D9%8A%D8%B7) in order to make sure that it is not misspelled. 

The suggested edit here is to write the Hamza below the Āalif (i.e. `الإلكتروني` instead of `الألكتروني`).  This is a good issue for newcomers. 

![josaform](https://user-images.githubusercontent.com/79845228/136592549-b02ad32f-42a3-4174-8410-971ced9c07a5.jpg)

**Comment by itsmohmans** [comment]
I'm working on this
